name: pokedex
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  http: ^0.13.5
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.0.0  # Adiciona suporte ao Linux para o sqflite

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
